### ISSUE TITLE
More fine grained user list

### ISSUE THREAD

**Issue by mkowsiak** [indigo-dc/fgAPIServer#30]
Currently, fgapiserver_ptvmap.json contains limited number of users.

Each portal user (authenticated via IAM) is mapped to one user inside fgAPIServer. This mapping rule is defined inside fgapiserver_ptvmap.json.

This approach leads to issues related to task management. E.g. two, different users can delete tasks one of each other.

**Comment by ricsxn** [comment]
How the PTV mapping works is defined in the  load_user function of fgapiserverx.py file
I’m reporting its description as written in the code:

                # Map the portal user with one of defined APIServer users
                # accordingly to the rules defined in fgapiserver_ptvmap.json
                # file. The json contains the list of possible APIServer
                # users with an associated list of possible portal users and
                # groups names that verify the mapping; below an example:
                #
                # fgapiserver_ptvmap.json: {
                #   "futuregateway":
                #        [ "group_a", ... "group_b", "user_a", "user_b", ... ]
                #   "test":
                #       [ "groupc", ... "group d", "user_c", ... "user d" .. ]
                #   "<APIServer user>":
                #      [ "<associated portal group>",
                #        "<associated portal_user>", ... ]
                # }
                #
                # If the PTV returns "user_a", "futuregateway" user will be
                # mapped, while if no mapping is available or portal_user and
                # groups are  not available a default user will be used,
                # see fgapisrv_ptvdefusr in configuration file

Unfortunately LiferayIAM does not return ‘user’ field: at most it is using the group value, so that you should need a group for each user in order to distinguish activities at user level.
However, LiferayIAM returns the subject field and I will modify the code in order to use it to separate user activities when it will be or null.
If you need a urgent test; you could apply the following change:

fgapiserverptv.py
138.        self.portal_subject = token_info.get('subject', None)
               if self.portal_subject is not None and self.portal_user = ‘’:
                   self.portal_user = self.portal_subject

I’m just forwarding the subject field into user field.
Then you can create FG users having as name the subject and use the PTV map file accordingly.

An example:

Subject

1) AAAAAAAAAAAAAAAAAA 1st user

insert into fg_user (name, password, first_name, last_name, institute, mail, creation, modified) values ('AAAAAAAAAAAAAAAAAA',password('Apassword'), 'A name', 'A lastname', 'A instituttion', 'A@mail', now(), now());


2) BBBBBBBBBBBBBBBBBB 2nd user

insert into fg_user (name, password, first_name, last_name, institute, mail, creation, modified) values ('BBBBBBBBBBBBBBBBBB',password('Bpassword'), 'B name', 'B lastname', 'B instituttion', 'B@mail', now(), now());


Then configure properly groups and roles (see table settings); you could assign the futuregateway’ group (admin) for simplicity

 fgapiserver_ptvmap.json {
….
     “AAAAAAAAAAAAAAAAAAAA”: 
	[ “AAAAAAAAAAAAAAAAAAAA” ] 
    “BBBBBBBBBBBBBBBBBBB”:
        [ “BBBBBBBBBBBBBBBBBB”]
…
}

With this configuration you should not have any overlapping between A and B users.

Rebgards,
Riccardo

**Comment by ricsxn** [comment]
Portal user isolation is now available under Issue#30 branch
