### ISSUE TITLE
ToscaIDC tasks should forward status from Orchestrator in runtime data

### ISSUE THREAD

**Issue by tzok** [indigo-dc/fgAPIServer#64]
Currently, when you submit a ToscaIDC-type of task, then three runtime data entries are automatically added: `tosca_endpoint`, `tosca_uuid` and `subject`. It would be useful to also have `tosca_status` (or named differently) which would be a field with status as returned by the Orchestrator e.g. `CREATE_IN_PROGRESS`.

**Comment by ricsxn** [comment]
I thought recently on something like this, because while discussing for the MD case using TOSCA, I noticed that it is totally missing a way to stay in touch with the orchestrator once you get the resource(s) from it (the UUID).
My idea would be to create a new Executor interface command for this, probably internally named GETRES. The aim of this EI command is to execute the orchestrator GET request with the UUID in order to get the returned json. This call is extremely important because contains references of all resources allocated. Once executed this command the way to recover the orchestrator json  file could be similar to the output files with the /files REST call.
The only problem is to map this new EI command with the existing API specs in a coherent fashion. This new command could be called using the same tip used for the TASK status change (PATCH).

(PUT) <APISERVER_ENDPOINT>/task/<task_id>

Data:

{
    “output_file”: “<orchestrator_returned_jsonfilename_youlike>”
}

Once the APIServerDaemon processes the command you can use the download output_files feature


curl -H "Authorization: Bearer TEST_TOKEN" "http://localhost/apis/v1.0/file?path=<task_path>&name=<orchestrator_returned_jsonfilename_youlike>"

Having this feature implement would fit your request.

**Comment by tzok** [comment]
Why not use ToscaIDC runtime data? You can put there the status of Orchestrator upon each update, it is easy and simple. 

Obtaining whole JSON is possible with cURL or Orchent for advanced scenarios anyway. We would need just the status.

**Comment by ricsxn** [comment]
Yes it is enough and also quite easy to implement because while getting the status of the task this information is available; on the other hand having the whole output of the orchestrator GET call on the UUID is a extremely important
However, this feature does not involves fgAPIServer component; so I'm opening it against the correct component APIServerDaemon and closing this issue.
